[package]
name = "smagical-backend-reducer"
version = "0.1.0"
edition = "2024"
rust-version = "1.95"

[dependencies]
smagical-backend-core = { path = "../smagical-backend-core" }
smagical-core = { path = "../smagical-core" }
smagical-session = { path = "../smagical-session" }
smagical-terminal = { path = "../smagical-terminal" }

[dev-dependencies]
uuid = { version = "1", features = ["v4"] }
