[package]
name = "smagical-ssh"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
authors.workspace = true
description = "Headless SSH, SFTP, Key Management, and Remote System Operations Engine"

[dependencies]
anyhow.workspace = true
tracing.workspace = true
tokio = { workspace = true, features = ["full"] }
serde = { workspace = true, features = ["derive"] }
serde_json.workspace = true
uuid.workspace = true
chrono = { workspace = true }
async-trait = { workspace = true }
russh = { workspace = true }
russh-sftp = { workspace = true }
smagical-core = { path = "../smagical-core" }
ssh-key = { workspace = true }
rand = { workspace = true }
directories = { workspace = true }
base64 = { workspace = true }



