[package]
name = "smagical-local-backend"
version = "0.1.0"
edition = "2024"
rust-version = "1.95"

[dependencies]
portable-pty = "0.9"
smagical-backend-core = { path = "../smagical-backend-core" }
smagical-core = { path = "../smagical-core" }
smagical-terminal = { path = "../smagical-terminal" }

[dev-dependencies]
uuid = { version = "1", features = ["v4"] }
