schema-version = 1
id = "builtin.ui.solarized-dark"
name = "Solarized Dark"
kind = "ui"
period = "night"
base = "builtin.ui.darcula"
author = "Ethan Schoonover"
source = "https://github.com/altercation/solarized"

[ui]
color-scheme = "dark"
window-background = "#002B36"
panel-background = "#073642"
surface-background = "#002B36"
control-background = "#073642"
foreground = "#839496"
secondary-foreground = "#657B83"
disabled-foreground = "#586E75"
accent = "#268BD2"
hover-background = "#0B4654"
pressed-background = "#155A68"
selected-background = "#245B73"
selected-foreground = "#FDF6E3"
border = "#1B5965"
focus-border = "#268BD2"
success = "#859900"
warning = "#B58900"
danger = "#DC322F"
info = "#2AA198"
