schema-version = 1
id = "builtin.ui.tokyo-night"
name = "Tokyo Night"
kind = "ui"
period = "night"
base = "builtin.ui.darcula"
author = "folke"
source = "https://github.com/folke/tokyonight.nvim"

[ui]
color-scheme = "dark"
window-background = "#1A1B26"
panel-background = "#16161E"
surface-background = "#24283B"
control-background = "#292E42"
foreground = "#C0CAF5"
secondary-foreground = "#A9B1D6"
disabled-foreground = "#565F89"
accent = "#7AA2F7"
hover-background = "#292E42"
pressed-background = "#3B4261"
selected-background = "#33467C"
selected-foreground = "#C0CAF5"
border = "#3B4261"
focus-border = "#7AA2F7"
success = "#9ECE6A"
warning = "#E0AF68"
danger = "#F7768E"
info = "#7DCFFF"
