[package]
name = "smagical-ui"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
authors.workspace = true
build = "build.rs"

[dependencies]
anyhow.workspace = true
rfd.workspace = true
slint.workspace = true
sys-locale.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
smagical-core = { path = "../smagical-core" }

[build-dependencies]
slint-build.workspace = true

[package.metadata.scripts]
extract-i18n = "../../.tools/slint-tr-extractor/bin/slint-tr-extractor.exe -o messages.po --package-name smagical-ui --package-version 0.1.0 --join-existing ui/main.slint"
