[package]
name = "smagical-ui"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
authors.workspace = true
build = "build.rs"

[dependencies]
anyhow.workspace = true
slint.workspace = true
tracing.workspace = true
portable-pty.workspace = true
alacritty_terminal.workspace = true
fontdue.workspace = true
arboard.workspace = true
vt100.workspace = true
directories.workspace = true
uuid.workspace = true
serde_json.workspace = true
smagical-core = { path = "../smagical-core" }
smagical-debug = { path = "../smagical-debug" }
image = { version = "0.25", default-features = false, features = ["png", "jpeg", "webp", "bmp"] }







[build-dependencies]
slint-build.workspace = true
