[package]
name = "smagical-ui"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
authors.workspace = true

[dependencies]
anyhow.workspace = true
slint.workspace = true
tracing.workspace = true
portable-pty.workspace = true
alacritty_terminal.workspace = true
fontdue.workspace = true
arboard.workspace = true
vt100.workspace = true
directories.workspace = true
uuid.workspace = true
regex = { workspace = true }
serde = { workspace = true, features = ["derive"] }
serde_json.workspace = true
tracing-subscriber = { workspace = true, features = ["env-filter", "fmt", "time", "json"] }
tracing-appender.workspace = true
smagical-core = { path = "../smagical-core" }
smagical-ssh = { path = "../smagical-ssh" }
smagical-storage = { path = "../smagical-storage" }
smagical-ui-view = { path = "../smagical-ui-view" }
image = { workspace = true }
winit = { workspace = true }
rfd = { workspace = true }
tokio = { workspace = true, features = ["full"] }
async-trait = { workspace = true }
reqwest = { workspace = true }
futures-util = { workspace = true }
chrono = { workspace = true }

[target.'cfg(windows)'.dependencies]
windows-sys = { workspace = true }

