[package]
name = "plugin-settings"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
authors.workspace = true

[dependencies]
slint.workspace = true
smagical-ui-common = { path = "../../common" }
smagical-core = { path = "../../../smagical-core" }
anyhow.workspace = true

[lib]
test = false
doctest = false
bench = false
