schema-version = 1
id = "builtin.terminal.rose-pine"
name = "Rosé Pine"
kind = "terminal"
author = "Rosé Pine"
source = "https://github.com/rose-pine/rose-pine-theme"
[terminal]
background = "#191724"
foreground = "#E0DEF4"
cursorColor = "#E0DEF4"
selectionBackground = "#403A5B"
black = "#26233A"
red = "#EB6F92"
green = "#9CCFD8"
yellow = "#F6C177"
blue = "#31748F"
purple = "#C4A7E7"
cyan = "#EBBCBA"
white = "#E0DEF4"
brightBlack = "#6E6A86"
brightRed = "#EB6F92"
brightGreen = "#9CCFD8"
brightYellow = "#F6C177"
brightBlue = "#31748F"
brightPurple = "#C4A7E7"
brightCyan = "#EBBCBA"
brightWhite = "#E0DEF4"
