schema-version = 1
id = "builtin.terminal.tokyo-night"
name = "Tokyo Night"
kind = "terminal"
author = "folke"
source = "https://github.com/folke/tokyonight.nvim"
[terminal]
background = "#1A1B26"
foreground = "#C0CAF5"
cursorColor = "#C0CAF5"
selectionBackground = "#33467C"
black = "#15161E"
red = "#F7768E"
green = "#41A6B5"
yellow = "#E0AF68"
blue = "#7AA2F7"
purple = "#BB9AF7"
cyan = "#7DCFFF"
white = "#787C99"
brightBlack = "#363B54"
brightRed = "#F7768E"
brightGreen = "#73DACA"
brightYellow = "#E0AF68"
brightBlue = "#7AA2F7"
brightPurple = "#BB9AF7"
brightCyan = "#7DCFFF"
brightWhite = "#ACB0D0"
