import { TunnelsDrawer } from "drawers/tunnels_drawer.slint";
import { TunnelsCenterView, TunnelItemData, JumpHopData } from "views/tunnels_center_view.slint";
import { CreateHostTunnelModal } from "modals/create-host-tunnel-modal.slint";
import { CreateTunnelTypeModal } from "modals/create-tunnel-type-modal.slint";

export component TunnelsView inherits TunnelsCenterView {}

export {
    TunnelsDrawer,
    TunnelsCenterView,
    CreateHostTunnelModal,
    CreateTunnelTypeModal,
}

export { TunnelItemData, JumpHopData }
