//! Slint 工作区状态写入。

use crate::app::AppWindow;
use crate::app::view_model::AppViewModel;

use super::theme::sync_theme_palette;

pub(super) fn sync_workspace_state(window: &AppWindow, model: &AppViewModel) {
    sync_theme_palette(window, model.theme_palette);
    window.set_host_count(model.host_count.as_str().into());
    window.set_tab_count(model.tab_count.as_str().into());
    window.set_active_page_key(model.active_page_key.into());
    window.set_active_page(model.active_page.into());
    window.set_language_label(model.language_label.into());
    let text = model.workspace_text;
    window.set_brand_short_label(text.brand_short.into());
    window.set_brand_name_label(text.brand_name.into());
    window.set_topbar_find_label(text.topbar_find.into());
    window.set_topbar_settings_label(text.topbar_settings.into());
    window.set_nav_find_label(text.topbar_find.into());
    window.set_nav_hosts_label(text.nav_hosts.into());
    window.set_nav_terminal_label(text.nav_terminal.into());
    window.set_nav_sftp_label(text.nav_sftp.into());
    window.set_nav_tunnels_label(text.nav_tunnels.into());
    window.set_nav_snippets_label(text.nav_snippets.into());
    window.set_nav_history_label(text.nav_history.into());
    window.set_nav_security_label(text.nav_security.into());
    window.set_nav_proxy_label(text.nav_proxy.into());
    window.set_nav_settings_label(text.nav_settings.into());
    window.set_host_new_label(text.host_new.into());
    window.set_host_open_label(text.host_open.into());
    window.set_host_files_label(text.host_files.into());
    window.set_host_edit_label(text.host_edit.into());
    window.set_host_delete_label(text.host_delete.into());
    window.set_host_duplicate_label(text.host_duplicate.into());
    window.set_host_delete_title_label(text.host_delete_title.into());
    window.set_host_delete_caption_label(text.host_delete_caption.into());
    window.set_host_delete_confirm_label(text.host_delete_confirm.into());
    window.set_host_delete_cancel_label(text.host_delete_cancel.into());
    window.set_group_create_host_label(text.group_create_host.into());
    window.set_group_create_group_label(text.group_create_group.into());
    window.set_group_delete_title_label(text.group_delete_title.into());
    window.set_group_delete_confirm_label(text.group_delete_confirm.into());
    window.set_group_delete_cancel_label(text.group_delete_cancel.into());
    window.set_tool_files_label(text.tool_files.into());
    window.set_tool_snippets_label(text.tool_snippets.into());
    window.set_tool_history_label(text.tool_history.into());
    window.set_tool_tunnels_label(text.tool_tunnels.into());
    window.set_tool_keys_label(text.tool_keys.into());
    window.set_tool_proxy_label(text.tool_proxy.into());
    window.set_proxy_empty_label(text.proxy_empty.into());
    window.set_proxy_section_route_label(text.proxy_section_route.into());
    window.set_proxy_section_forward_label(text.proxy_section_forward.into());
    window.set_proxy_section_host_label(text.proxy_section_host.into());
    window.set_proxy_jump_caption_label(text.proxy_jump_caption.into());
    window.set_proxy_command_caption_label(text.proxy_command_caption.into());
    window.set_proxy_forward_caption_label(text.proxy_forward_caption.into());
    window.set_proxy_host_hint_caption_label(text.proxy_host_hint_caption.into());
    window.set_proxy_runtime_section_label(text.proxy_runtime_section.into());
    window.set_proxy_resources_section_label(text.proxy_resources_section.into());
    window.set_proxy_runtime_empty_label(text.proxy_runtime_empty.into());
    window.set_proxy_resources_empty_label(text.proxy_resources_empty.into());
    window.set_proxy_search_placeholder_label(text.proxy_search_placeholder.into());
    window.set_proxy_search_empty_label(text.proxy_search_empty.into());
    window.set_proxy_clear_selection_label(text.proxy_clear_selection.into());
    window.set_proxy_new_proxy_label(text.proxy_new_proxy.into());
    window.set_proxy_new_jump_label(text.proxy_new_jump.into());
    window.set_proxy_new_forward_label(text.proxy_new_forward.into());
    window.set_proxy_edit_label(text.proxy_edit.into());
    window.set_proxy_delete_label(text.proxy_delete.into());
    window.set_proxy_save_label(text.proxy_save.into());
    window.set_proxy_cancel_label(text.proxy_cancel.into());
    window.set_proxy_delete_title_label(text.proxy_delete_title.into());
    window.set_proxy_delete_caption_label(text.proxy_delete_caption.into());
    window.set_proxy_name_label(text.proxy_name_label.into());
    window.set_proxy_name_placeholder(text.proxy_name_placeholder.into());
    window.set_proxy_address_label(text.proxy_address_label.into());
    window.set_proxy_port_label(text.proxy_port_label.into());
    window.set_proxy_tags_label(text.proxy_tags_label.into());
    window.set_proxy_bind_label(text.proxy_bind_label.into());
    window.set_proxy_target_label(text.proxy_target_label.into());
    window.set_proxy_host_ids_label(text.proxy_host_ids_label.into());
    window.set_proxy_note_label(text.proxy_note_label.into());
    window.set_proxy_used_by_label(text.proxy_used_by_label.into());
    window.set_proxy_host_ids_placeholder(text.proxy_host_ids_placeholder.into());
    window.set_proxy_bind_host_placeholder(text.proxy_bind_host_placeholder.into());
    window.set_proxy_target_host_placeholder(text.proxy_target_host_placeholder.into());
    window.set_proxy_tags_placeholder(text.proxy_tags_placeholder.into());
    window.set_proxy_auto_start_label(text.proxy_auto_start.into());
    window.set_proxy_exit_on_failure_label(text.proxy_exit_on_failure.into());
    window.set_proxy_auth_none_label(text.proxy_auth_none.into());
    window.set_proxy_auth_user_password_label(text.proxy_auth_user_password.into());
    window.set_proxy_auth_username_label(text.proxy_auth_username.into());
    window.set_proxy_auth_password_ref_label(text.proxy_auth_password_ref.into());
    window.set_proxy_remote_dns_label(text.proxy_remote_dns.into());
    window.set_proxy_kind_socks5_label(text.proxy_kind_socks5.into());
    window.set_proxy_kind_http_label(text.proxy_kind_http.into());
    window.set_proxy_kind_local_label(text.proxy_kind_local.into());
    window.set_proxy_kind_remote_label(text.proxy_kind_remote.into());
    window.set_proxy_kind_dynamic_label(text.proxy_kind_dynamic.into());
    window.set_security_tree_title_label(text.security_tree_title.into());
    window.set_security_search_placeholder_label(text.security_search_placeholder.into());
    window.set_security_new_label(text.security_new.into());
    window.set_security_create_action_title_label(text.security_create_action_title.into());
    window.set_security_create_action_create_label(text.security_create_action_create.into());
    window.set_security_create_action_create_caption_label(
        text.security_create_action_create_caption.into(),
    );
    window.set_security_create_action_import_label(text.security_create_action_import.into());
    window.set_security_create_action_import_caption_label(
        text.security_create_action_import_caption.into(),
    );
    window.set_security_create_action_group_caption_label(
        text.security_create_action_group_caption.into(),
    );
    window.set_security_create_type_title_label(text.security_create_type_title.into());
    window.set_security_create_type_create_caption_label(
        text.security_create_type_create_caption.into(),
    );
    window.set_security_create_type_import_caption_label(
        text.security_create_type_import_caption.into(),
    );
    window.set_security_group_new_label(text.security_group_new.into());
    window.set_security_group_edit_label(text.security_group_edit.into());
    window.set_security_group_delete_label(text.security_group_delete.into());
    window.set_security_private_keys_label(text.security_private_keys.into());
    window.set_security_certificates_label(text.security_certificates.into());
    window.set_security_passwords_label(text.security_passwords.into());
    window.set_security_agents_label(text.security_agents.into());
    window.set_security_private_key_create_label(text.security_private_key_create.into());
    window.set_security_private_key_import_label(text.security_private_key_import.into());
    window.set_security_certificate_create_label(text.security_certificate_create.into());
    window.set_security_certificate_import_label(text.security_certificate_import.into());
    window.set_security_password_create_label(text.security_password_create.into());
    window.set_security_agent_create_label(text.security_agent_create.into());
    window
        .set_security_private_key_create_title_label(text.security_private_key_create_title.into());
    window
        .set_security_private_key_import_title_label(text.security_private_key_import_title.into());
    window
        .set_security_certificate_create_title_label(text.security_certificate_create_title.into());
    window
        .set_security_certificate_import_title_label(text.security_certificate_import_title.into());
    window.set_security_password_create_title_label(text.security_password_create_title.into());
    window.set_security_agent_create_title_label(text.security_agent_create_title.into());
    window.set_security_credential_name_label(text.security_credential_name_label.into());
    window
        .set_security_credential_name_placeholder(text.security_credential_name_placeholder.into());
    window.set_security_credential_secret_label(text.security_credential_secret_label.into());
    window.set_security_private_key_secret_placeholder(
        text.security_private_key_secret_placeholder.into(),
    );
    window.set_security_certificate_secret_placeholder(
        text.security_certificate_secret_placeholder.into(),
    );
    window.set_security_password_secret_label(text.security_password_secret_label.into());
    window
        .set_security_password_secret_placeholder(text.security_password_secret_placeholder.into());
    window.set_security_password_show_label(text.security_password_show.into());
    window.set_security_password_hide_label(text.security_password_hide.into());
    window.set_security_agent_secret_label(text.security_agent_secret_label.into());
    window.set_security_agent_secret_placeholder(text.security_agent_secret_placeholder.into());
    window.set_security_private_key_source_label(text.security_private_key_source_label.into());
    window.set_security_private_key_source_placeholder(
        text.security_private_key_source_placeholder.into(),
    );
    window.set_security_private_key_import_file_label(text.security_private_key_import_file.into());
    window.set_security_private_key_import_text_label(text.security_private_key_import_text.into());
    window.set_security_private_key_text_label(text.security_private_key_text_label.into());
    window.set_security_private_key_text_placeholder(
        text.security_private_key_text_placeholder.into(),
    );
    window.set_security_certificate_source_label(text.security_certificate_source_label.into());
    window.set_security_certificate_source_placeholder(
        text.security_certificate_source_placeholder.into(),
    );
    window.set_security_certificate_text_label(text.security_certificate_text_label.into());
    window.set_security_certificate_text_placeholder(
        text.security_certificate_text_placeholder.into(),
    );
    window.set_security_certificate_ca_key_label(text.security_certificate_ca_key_label.into());
    window.set_security_certificate_ca_key_placeholder(
        text.security_certificate_ca_key_placeholder.into(),
    );
    window.set_security_certificate_subject_key_label(
        text.security_certificate_subject_key_label.into(),
    );
    window.set_security_certificate_subject_key_placeholder(
        text.security_certificate_subject_key_placeholder.into(),
    );
    window.set_security_certificate_type_label(text.security_certificate_type_label.into());
    window.set_security_certificate_type_user_label(text.security_certificate_type_user.into());
    window.set_security_certificate_type_host_label(text.security_certificate_type_host.into());
    window.set_security_certificate_principals_label(
        text.security_certificate_principals_label.into(),
    );
    window.set_security_certificate_principals_placeholder(
        text.security_certificate_principals_placeholder.into(),
    );
    window.set_security_certificate_valid_days_label(
        text.security_certificate_valid_days_label.into(),
    );
    window.set_security_certificate_valid_days_placeholder(
        text.security_certificate_valid_days_placeholder.into(),
    );
    window.set_security_certificate_key_id_label(text.security_certificate_key_id_label.into());
    window.set_security_certificate_key_id_placeholder(
        text.security_certificate_key_id_placeholder.into(),
    );
    window.set_security_certificate_serial_label(text.security_certificate_serial_label.into());
    window.set_security_certificate_serial_placeholder(
        text.security_certificate_serial_placeholder.into(),
    );
    window.set_security_certificate_key_picker_title_label(
        text.security_certificate_key_picker_title.into(),
    );
    window.set_security_certificate_empty_private_keys_label(
        text.security_certificate_empty_private_keys.into(),
    );
    window.set_security_credential_algorithm_label(text.security_credential_algorithm_label.into());
    window.set_security_credential_save_label(text.security_credential_save.into());
    window.set_security_credential_generating_private_key_label(
        text.security_credential_generating_private_key.into(),
    );
    window.set_security_credential_edit_label(text.security_credential_edit.into());
    window.set_security_credential_move_label(text.security_credential_move.into());
    window.set_security_credential_duplicate_label(text.security_credential_duplicate.into());
    window.set_security_credential_export_label(text.security_credential_export.into());
    window.set_security_credential_replace_secret_label(
        text.security_credential_replace_secret.into(),
    );
    window.set_security_credential_delete_label(text.security_credential_delete.into());
    window.set_security_credential_delete_title_label(text.security_credential_delete_title.into());
    window.set_security_credential_delete_caption_label(
        text.security_credential_delete_caption.into(),
    );
    window.set_security_credential_delete_confirm_label(
        text.security_credential_delete_confirm.into(),
    );
    window
        .set_security_credential_delete_cancel_label(text.security_credential_delete_cancel.into());
    window.set_security_credential_export_title_label(text.security_credential_export_title.into());
    window.set_security_credential_export_path_label(
        text.security_credential_export_path_label.into(),
    );
    window.set_security_credential_export_path_placeholder(
        text.security_credential_export_path_placeholder.into(),
    );
    window.set_security_credential_replace_secret_title_label(
        text.security_credential_replace_secret_title.into(),
    );
    window.set_security_credential_replace_secret_field_label(
        text.security_credential_replace_secret_label.into(),
    );
    window.set_security_credential_replace_secret_placeholder(
        text.security_credential_replace_secret_placeholder.into(),
    );
    window.set_security_credential_replace_secret_confirm_title_label(
        text.security_credential_replace_secret_confirm_title.into(),
    );
    window.set_security_credential_replace_secret_confirm_caption_label(
        text.security_credential_replace_secret_confirm_caption
            .into(),
    );
    window.set_security_credential_replace_secret_confirm_label(
        text.security_credential_replace_secret_confirm.into(),
    );
    window.set_security_credential_edit_private_key_label(
        text.security_credential_edit_private_key.into(),
    );
    window.set_security_credential_edit_certificate_label(
        text.security_credential_edit_certificate.into(),
    );
    window
        .set_security_credential_edit_password_label(text.security_credential_edit_password.into());
    window.set_security_view_content_label(text.security_view_content.into());
    window.set_security_view_private_key_label(text.security_view_private_key.into());
    window.set_security_view_certificate_label(text.security_view_certificate.into());
    window.set_security_view_password_label(text.security_view_password.into());
    window.set_security_secret_copy_label(text.security_secret_copy.into());
    window.set_security_secret_copy_success_label(text.security_secret_copy_success.into());
    window.set_security_secret_copy_failed_label(text.security_secret_copy_failed.into());
    window.set_security_secret_content_missing_label(text.security_secret_content_missing.into());
    window.set_security_detail_empty_title_label(text.security_detail_empty_title.into());
    window.set_security_detail_empty_caption_label(text.security_detail_empty_caption.into());
    window.set_security_field_type_label(text.security_field_type.into());
    window.set_security_field_username_label(text.security_field_username.into());
    window.set_security_field_algorithm_label(text.security_field_algorithm.into());
    window.set_security_field_fingerprint_label(text.security_field_fingerprint.into());
    window.set_security_field_secret_ref_label(text.security_field_secret_ref.into());
    window.set_security_field_group_label(text.security_field_group.into());
    window.set_security_group_caption_label(text.security_group_caption.into());
    window.set_host_search_placeholder(text.host_search_placeholder.into());
    window.set_hosts_section_title(text.hosts_section_title.into());
    window.set_hosts_empty_title(text.hosts_empty_title.into());
    window.set_hosts_empty_caption(text.hosts_empty_caption.into());
    window.set_activity_title_label(text.activity_title.into());
    window.set_recent_title_label(text.recent_title.into());
    window.set_recent_empty_label(text.recent_empty.into());
    window.set_command_palette_title_label(text.command_palette_title.into());
    window.set_command_palette_placeholder(text.command_palette_placeholder.into());
    window.set_command_palette_empty_label(text.command_palette_empty.into());
    window.set_command_palette_close_label(text.command_palette_close.into());
    window.set_new_session_title_label(text.new_session_title.into());
    window.set_new_session_search_placeholder(text.new_session_search_placeholder.into());
    window.set_new_session_local_title(text.new_session_local_title.into());
    window.set_new_session_local_subtitle(text.new_session_local_subtitle.into());
    window.set_new_session_local_detail(text.new_session_local_detail.into());
    window.set_new_session_local_tags(text.new_session_local_tags.into());
    window.set_new_session_local_status(text.new_session_local_status.into());
    window.set_new_session_local_kind(text.new_session_local_kind.into());
    window.set_new_session_remote_kind(text.new_session_remote_kind.into());
    window.set_new_session_ungrouped_detail(text.new_session_ungrouped_detail.into());
    window.set_new_session_empty_title(text.new_session_empty_title.into());
    window.set_new_session_empty_caption(text.new_session_empty_caption.into());
    window.set_terminal_reconnect_label(text.terminal_reconnect.into());
    window.set_tab_ready_label(text.tab_ready.into());
    window.set_sftp_loading_label(text.sftp_loading.into());
    window.set_sftp_split_title(text.sftp_split_title.into());
    window.set_sftp_refresh_label(text.sftp_refresh.into());
    window.set_sftp_local_title(text.sftp_local_title.into());
    window.set_sftp_remote_title(text.sftp_remote_title.into());
    window.set_sftp_workspace_label(text.sftp_workspace_label.into());
    window.set_sftp_queue_label(text.sftp_queue_label.into());
    window.set_sftp_selected_label(text.sftp_selected_label.into());
    window.set_sftp_path_label(text.sftp_path_label.into());
    window.set_sftp_entries_label(text.sftp_entries_label.into());
    window.set_sftp_loading_entries_label(text.sftp_loading_entries.into());
    window.set_sftp_empty_entries_label(text.sftp_empty_entries.into());
    window.set_tool_pinned_label(text.tool_pinned.into());
    window.set_tool_empty_value_label(text.tool_empty_value.into());
    window.set_snippets_tree_title_label(text.snippets_tree_title.into());
    window.set_snippets_search_placeholder_label(text.snippets_search_placeholder.into());
    window.set_snippets_detail_empty_title_label(text.snippets_detail_empty_title.into());
    window.set_snippets_detail_empty_caption_label(text.snippets_detail_empty_caption.into());
    window.set_snippets_field_scope_label(text.snippets_field_scope.into());
    window.set_snippets_field_variables_label(text.snippets_field_variables.into());
    window.set_snippets_field_arguments_label(text.snippets_field_arguments.into());
    window.set_snippets_command_template_label(text.snippets_command_template.into());
    window.set_snippets_group_caption_label(text.snippets_group_caption.into());
    window.set_snippets_description_empty_label(text.snippets_description_empty.into());
    window.set_snippets_new_label(text.snippets_new.into());
    window.set_snippets_new_snippet_label(text.snippets_new_snippet.into());
    window.set_snippets_new_snippet_caption_label(text.snippets_new_snippet_caption.into());
    window.set_snippets_new_target_label(text.snippets_new_target.into());
    window.set_snippets_new_group_label(text.snippets_new_group.into());
    window.set_snippets_new_group_caption_label(text.snippets_new_group_caption.into());
    window.set_snippets_create_choice_title_label(text.snippets_create_choice_title.into());
    window.set_snippets_group_contents_title_label(text.snippets_group_contents_title.into());
    window.set_snippets_target_variant_title_label(text.snippets_target_variant_title.into());
    window.set_snippets_script_relation_label(text.snippets_script_relation.into());
    window.set_snippets_script_shared_label(text.snippets_script_shared.into());
    window.set_snippets_script_independent_label(text.snippets_script_independent.into());
    window.set_snippets_create_snippet_title_label(text.snippets_create_snippet_title.into());
    window.set_snippets_create_target_title_label(text.snippets_create_target_title.into());
    window.set_snippets_create_group_title_label(text.snippets_create_group_title.into());
    window.set_snippets_edit_snippet_title_label(text.snippets_edit_snippet_title.into());
    window.set_snippets_edit_target_title_label(text.snippets_edit_target_title.into());
    window.set_snippets_edit_group_title_label(text.snippets_edit_group_title.into());
    window.set_snippets_edit_label(text.snippets_edit.into());
    window.set_snippets_delete_label(text.snippets_delete.into());
    window.set_snippets_delete_title_label(text.snippets_delete_title.into());
    window.set_snippets_delete_snippet_caption_label(text.snippets_delete_snippet_caption.into());
    window.set_snippets_delete_group_caption_label(text.snippets_delete_group_caption.into());
    window.set_snippets_delete_target_caption_label(text.snippets_delete_target_caption.into());
    window.set_snippets_delete_confirm_label(text.snippets_delete_confirm.into());
    window.set_snippets_copy_label(text.snippets_copy.into());
    window.set_snippets_copy_success_label(text.snippets_copy_success.into());
    window.set_snippets_copy_failed_label(text.snippets_copy_failed.into());
    window.set_snippets_run_label(text.snippets_run.into());
    window.set_snippets_run_title_label(text.snippets_run_title.into());
    window.set_snippets_run_host_label(text.snippets_run_host_label.into());
    window.set_snippets_run_arguments_label(text.snippets_run_arguments_label.into());
    window.set_snippets_run_arguments_placeholder_label(
        text.snippets_run_arguments_placeholder.into(),
    );
    window.set_snippets_run_no_hosts_label(text.snippets_run_no_hosts.into());
    window.set_snippets_move_label(text.snippets_move.into());
    window.set_snippets_move_title_label(text.snippets_move_title.into());
    window.set_snippets_move_root_label(text.snippets_move_root.into());
    window.set_snippets_choose_group_label(text.snippets_choose_group.into());
    window.set_snippets_confirm_group_label(text.snippets_confirm_group.into());
    window.set_snippets_name_label(text.snippets_name_label.into());
    window.set_snippets_name_placeholder_label(text.snippets_name_placeholder.into());
    window.set_snippets_group_name_placeholder_label(text.snippets_group_name_placeholder.into());
    window.set_snippets_description_label(text.snippets_description_label.into());
    window.set_snippets_description_placeholder_label(text.snippets_description_placeholder.into());
    window.set_snippets_target_key_label(text.snippets_target_key_label.into());
    window.set_snippets_target_key_placeholder_label(text.snippets_target_key_placeholder.into());
    window.set_snippets_target_picker_placeholder_label(
        text.snippets_target_picker_placeholder.into(),
    );
    window.set_snippets_target_linux_label(text.snippets_target_linux.into());
    window.set_snippets_target_debian_label(text.snippets_target_debian.into());
    window.set_snippets_target_rhel_label(text.snippets_target_rhel.into());
    window.set_snippets_target_alpine_label(text.snippets_target_alpine.into());
    window.set_snippets_target_fedora_label(text.snippets_target_fedora.into());
    window.set_snippets_target_arch_label(text.snippets_target_arch.into());
    window.set_snippets_target_suse_label(text.snippets_target_suse.into());
    window.set_snippets_target_freebsd_label(text.snippets_target_freebsd.into());
    window.set_snippets_target_macos_label(text.snippets_target_macos.into());
    window.set_snippets_target_powershell_label(text.snippets_target_powershell.into());
    window.set_snippets_target_cmd_label(text.snippets_target_cmd.into());
    window.set_snippets_command_placeholder_label(text.snippets_command_placeholder.into());
    window.set_snippets_target_mode_new_label(text.snippets_target_mode_new.into());
    window.set_snippets_target_mode_new_caption_label(text.snippets_target_mode_new_caption.into());
    window.set_snippets_target_mode_share_label(text.snippets_target_mode_share.into());
    window.set_snippets_target_mode_share_caption_label(
        text.snippets_target_mode_share_caption.into(),
    );
    window.set_snippets_shared_target_label(text.snippets_shared_target.into());
    window.set_snippets_split_target_label(text.snippets_split_target.into());
    window.set_snippets_cancel_label(text.snippets_cancel.into());
    window.set_snippets_create_label(text.snippets_create.into());
    window.set_snippets_save_label(text.snippets_save.into());
    window.set_snippets_empty_label(text.snippets_empty.into());
    window.set_history_commands_label(text.history_commands.into());
    window.set_history_saved_suffix_label(text.history_saved_suffix.into());
    window.set_history_empty_label(text.history_empty.into());
    window.set_history_run_label(text.history_run.into());
    window.set_tunnels_empty_label(text.tunnels_empty.into());
    window.set_known_hosts_empty_label(text.known_hosts_empty.into());
    window.set_known_hosts_trust_label(text.known_hosts_trust.into());
    window.set_known_hosts_delete_label(text.known_hosts_delete.into());
    let settings = &model.settings_workspace.settings;
    window.set_settings_title_label(settings.text.title.into());
    window.set_settings_language_title_label(settings.text.language_title.into());
    window.set_settings_theme_title_label(settings.text.theme_title.into());
    window.set_settings_custom_theme_title_label(settings.text.custom_theme_title.into());
    window.set_settings_storage_title_label(settings.text.storage_title.into());
    window.set_settings_file_actions_title_label(settings.text.file_actions_title.into());
    window.set_settings_security_title_label(settings.text.security_title.into());
    window.set_settings_apply_label(settings.text.apply_label.into());
    window.set_settings_copy_label(settings.text.copy_label.into());
    window.set_settings_remove_label(settings.text.remove_label.into());
    window.set_settings_run_label(settings.text.run_label.into());
    window.set_settings_choose_file_label(settings.text.choose_file_label.into());
    window.set_settings_selected_label(settings.text.selected_label.into());
    window.set_settings_unavailable_label(settings.text.unavailable_label.into());
    window.set_settings_empty_custom_themes_label(settings.text.no_custom_themes_label.into());
    window.set_settings_current_profile_name(settings.theme.current_profile_name.as_str().into());
    window.set_settings_storage_summary_label(settings.storage_summary.as_str().into());
    window.set_settings_storage_backend_label(settings.storage.backend_label.into());
    window.set_settings_storage_database_path(settings.storage.database_path.as_str().into());
    window.set_settings_security_summary_label(settings.security_summary.into());
    window.set_settings_security_status_label(settings.security.status_label.into());
    window.set_settings_security_detail_label(settings.security.detail_label.into());
    window.set_settings_security_kdf_label(settings.security.kdf_label.into());
    window.set_settings_security_version_label(settings.security.encryption_version_label.into());
    window.set_theme_name(model.theme_name.into());
    window.set_background_summary(model.background_summary.as_str().into());
    window.set_host_list_mode_key(model.host_list_mode_key.into());
    window.set_host_list_mode(model.host_list_mode.into());
    window.set_host_search_query(model.host_search_query.as_str().into());
    window.set_credential_search_query(model.security_workspace.search_query.as_str().into());
    window.set_snippet_search_query(model.snippet_workspace.search_query.as_str().into());
    window.set_network_search_query(model.network_workspace.search_query.as_str().into());
    window.set_create_host_dialog_open(model.create_host_dialog_open);
    window.set_create_group_parent_dialog_open(model.create_group_parent_dialog_open);
    window.set_create_group_dialog_open(model.create_group_dialog_open);
    window.set_remove_host_dialog_open(model.remove_host_dialog_open);
    window.set_remove_host_dialog_name(model.remove_host_dialog_name.as_str().into());
    window.set_remove_group_dialog_open(model.remove_group_dialog_open);
    window.set_remove_group_dialog_name(model.remove_group_dialog_name.as_str().into());
    window.set_remove_group_dialog_caption(model.remove_group_dialog_caption.into());
    let create_host = model.create_host_dialog;
    let create_choice = model.create_choice;
    window.set_create_choice_title(create_choice.title.into());
    window.set_create_choice_subtitle(create_choice.subtitle.into());
    window.set_create_choice_host_label(create_choice.host_label.into());
    window.set_create_choice_host_caption(create_choice.host_caption.into());
    window.set_create_choice_group_label(create_choice.group_label.into());
    window.set_create_choice_group_caption(create_choice.group_caption.into());
    window.set_create_choice_cancel_label(create_choice.cancel_label.into());
    window.set_create_host_dialog_title(create_host.dialog_title.into());
    window.set_create_host_dialog_subtitle(create_host.dialog_subtitle.into());
    window.set_create_host_connection_title(create_host.connection_title.into());
    window.set_create_host_connection_caption(create_host.connection_caption.into());
    window.set_create_host_authentication_title(create_host.authentication_title.into());
    window.set_create_host_authentication_caption(create_host.authentication_caption.into());
    window.set_create_host_credential_note(create_host.credential_note.into());
    window.set_create_host_cancel_label(create_host.cancel_label.into());
    window.set_create_host_create_label(create_host.create_label.into());
    window.set_create_host_address_label(create_host.address_label.into());
    window.set_create_host_address_placeholder(create_host.address_placeholder.into());
    window.set_create_host_port_label(create_host.port_label.into());
    window.set_create_host_port_placeholder(create_host.port_placeholder.into());
    window.set_create_host_username_label(create_host.username_label.into());
    window.set_create_host_username_placeholder(create_host.username_placeholder.into());
    window.set_create_host_alias_label(create_host.host_alias_label.into());
    window.set_create_host_alias_placeholder(create_host.host_alias_placeholder.into());
    window.set_create_host_tags_label(create_host.tags_label.into());
    window.set_create_host_tags_placeholder(create_host.tags_placeholder.into());
    window.set_create_host_group_label(create_host.group_label.into());
    window.set_create_host_group_picker_title(create_host.group_picker_title.into());
    window.set_create_host_auth_agent_label(create_host.auth_agent_label.into());
    window.set_create_host_auth_agent_caption(create_host.auth_agent_caption.into());
    window.set_create_host_auth_password_label(create_host.auth_password_label.into());
    window.set_create_host_auth_password_caption(create_host.auth_password_caption.into());
    window.set_create_host_auth_key_label(create_host.auth_key_label.into());
    window.set_create_host_auth_key_caption(create_host.auth_key_caption.into());
    window.set_create_host_auth_certificate_label(create_host.auth_certificate_label.into());
    window.set_create_host_auth_certificate_caption(create_host.auth_certificate_caption.into());
    window.set_create_host_agent_source_title(create_host.agent_source_title.into());
    window.set_create_host_agent_auto_label(create_host.agent_auto_label.into());
    window.set_create_host_agent_auto_caption(create_host.agent_auto_caption.into());
    window.set_create_host_agent_openssh_label(create_host.agent_openssh_label.into());
    window.set_create_host_agent_openssh_caption(create_host.agent_openssh_caption.into());
    window.set_create_host_agent_pageant_label(create_host.agent_pageant_label.into());
    window.set_create_host_agent_pageant_caption(create_host.agent_pageant_caption.into());
    window.set_create_host_agent_custom_label(create_host.agent_custom_label.into());
    window.set_create_host_agent_custom_caption(create_host.agent_custom_caption.into());
    window.set_create_host_custom_agent_pipe_label(create_host.custom_agent_pipe_label.into());
    window.set_create_host_custom_agent_pipe_placeholder(
        create_host.custom_agent_pipe_placeholder.into(),
    );
    window.set_create_host_agent_key_hint_label(create_host.agent_key_hint_label.into());
    window
        .set_create_host_agent_key_hint_placeholder(create_host.agent_key_hint_placeholder.into());
    window.set_create_host_password_secret_label(create_host.password_secret_label.into());
    window.set_create_host_password_secret_placeholder(
        create_host.password_secret_placeholder.into(),
    );
    window.set_create_host_private_key_label(create_host.private_key_label.into());
    window.set_create_host_private_key_placeholder(create_host.private_key_placeholder.into());
    window.set_create_host_add_private_key_label(create_host.add_private_key_label.into());
    window.set_create_host_add_private_key_caption(create_host.add_private_key_caption.into());
    window.set_create_host_passphrase_label(create_host.passphrase_label.into());
    window.set_create_host_passphrase_placeholder(create_host.passphrase_placeholder.into());
    window.set_create_host_certificate_label(create_host.certificate_label.into());
    window.set_create_host_certificate_placeholder(create_host.certificate_placeholder.into());
    window.set_create_host_add_certificate_label(create_host.add_certificate_label.into());
    window.set_create_host_add_certificate_caption(create_host.add_certificate_caption.into());
    window.set_create_host_credential_name_label(create_host.credential_name_label.into());
    window.set_create_host_credential_name_placeholder(
        create_host.credential_name_placeholder.into(),
    );
    window.set_create_host_credential_secret_label(create_host.credential_secret_label.into());
    window.set_create_host_credential_secret_placeholder(
        create_host.credential_secret_placeholder.into(),
    );
    window
        .set_create_host_credential_algorithm_label(create_host.credential_algorithm_label.into());
    window.set_create_host_credential_save_label(create_host.credential_save_label.into());
    window.set_create_host_network_title(create_host.network_title.into());
    window.set_create_host_network_caption(create_host.network_caption.into());
    window.set_create_host_network_proxy_label(create_host.network_proxy_label.into());
    window.set_create_host_network_jump_label(create_host.network_jump_label.into());
    window.set_create_host_network_forward_label(create_host.network_forward_label.into());
    window.set_create_host_network_empty_label(create_host.network_empty_label.into());
    window.set_create_host_icon_title(create_host.icon_title.into());
    window.set_create_host_icon_server_label(create_host.icon_server_label.into());
    window.set_create_host_icon_database_label(create_host.icon_database_label.into());
    window.set_create_host_icon_cloud_label(create_host.icon_cloud_label.into());
    window.set_create_host_icon_linux_label(create_host.icon_linux_label.into());
    window.set_create_host_icon_container_label(create_host.icon_container_label.into());
    window.set_create_host_icon_shield_label(create_host.icon_shield_label.into());
    window.set_create_host_icon_router_label(create_host.icon_router_label.into());
    window.set_create_host_icon_terminal_label(create_host.icon_terminal_label.into());
    window.set_create_host_icon_globe_label(create_host.icon_globe_label.into());
    window.set_create_host_icon_key_label(create_host.icon_key_label.into());
    window.set_create_host_icon_chip_label(create_host.icon_chip_label.into());
    window.set_create_host_icon_cluster_label(create_host.icon_cluster_label.into());
    let create_group = &model.create_group_dialog;
    window.set_create_group_dialog_title(create_group.title.into());
    window.set_create_group_dialog_subtitle(create_group.subtitle.into());
    window.set_create_group_parent_picker_title(create_group.parent_picker_title.into());
    window.set_create_group_parent_picker_subtitle(create_group.parent_picker_subtitle.into());
    window.set_create_group_name_label(create_group.name_label.into());
    window.set_create_group_name_placeholder(create_group.name_placeholder.into());
    window.set_create_group_parent_label(create_group.parent_label.into());
    window.set_create_group_cancel_label(create_group.cancel_label.into());
    window.set_create_group_save_label(create_group.save_label.into());
    window.set_create_group_next_label(create_group.next_label.into());
    window.set_quick_group_parent_path(create_group.parent_path.as_str().into());
    window.set_quick_group_name(create_group.name.as_str().into());
    window.set_quick_host_name(model.quick_host.name.as_str().into());
    window.set_quick_host_address(model.quick_host.address.as_str().into());
    window.set_quick_host_port(model.quick_host.port.as_str().into());
    window.set_quick_host_username(model.quick_host.username.as_str().into());
    window.set_quick_host_group_path(model.quick_host.group_path.as_str().into());
    window.set_quick_host_icon_key(model.quick_host.icon_key.as_str().into());
    window.set_quick_host_tags(model.quick_host.tags.as_str().into());
    window.set_quick_host_auth_kind(model.quick_host.auth_kind.into());
    window.set_quick_host_agent_source(model.quick_host.agent_source.into());
    window.set_quick_host_agent_custom_pipe(model.quick_host.agent_custom_pipe.as_str().into());
    window.set_quick_host_password_secret_ref(model.quick_host.password_secret_ref.as_str().into());
    window.set_quick_host_private_key_ref(model.quick_host.private_key_ref.as_str().into());
    window.set_quick_host_passphrase_ref(model.quick_host.passphrase_ref.as_str().into());
    window.set_quick_host_key_hint(model.quick_host.key_hint.as_str().into());
    window.set_quick_host_certificate_ref(model.quick_host.certificate_ref.as_str().into());
    window.set_hosts_panel_collapsed(model.hosts_panel_collapsed);
    window.set_hosts_panel_width(model.hosts_panel_width);
    window.set_activity_panel_width(model.activity_panel_width);
    window.set_tool_panel_width(model.terminal_workspace.tool_panel_width);
    window.set_tool_panel_mode_key(model.terminal_workspace.tool_panel_mode_key.into());
    window.set_tool_panel_mode(model.terminal_workspace.tool_panel_mode.into());
    window.set_right_sidebar_collapsed(model.right_sidebar_collapsed);
    window.set_last_error(model.last_error.as_str().into());
    window.set_command_palette_open(model.command_palette_open);
    window.set_command_palette_query(model.command_palette_query.as_str().into());
    window.set_new_session_search_query(model.new_session_search_query.as_str().into());
    window.set_new_session_local_visible(model.new_session_local_visible);
}
