schema-version = 1
id = "builtin.ui.catppuccin-mocha"
name = "Catppuccin Mocha"
kind = "ui"
period = "night"
base = "builtin.ui.darcula"
author = "Catppuccin"
source = "https://github.com/catppuccin/catppuccin"

[ui]
color-scheme = "dark"
window-background = "#1E1E2E"
panel-background = "#181825"
surface-background = "#313244"
control-background = "#45475A"
foreground = "#CDD6F4"
secondary-foreground = "#A6ADC8"
disabled-foreground = "#6C7086"
accent = "#89B4FA"
hover-background = "#45475A"
pressed-background = "#585B70"
selected-background = "#585B70"
selected-foreground = "#F5E0E6"
border = "#585B70"
focus-border = "#89B4FA"
success = "#A6E3A1"
warning = "#F9E2AF"
danger = "#F38BA8"
info = "#89DCEB"
