schema-version = 1
id = "builtin.ui.monokai"
name = "Monokai"
kind = "ui"
period = "night"
base = "builtin.ui.darcula"
author = "Monokai"
source = "https://monokai.pro"

[ui]
color-scheme = "dark"
window-background = "#272822"
panel-background = "#2E2F2A"
surface-background = "#3E3D32"
control-background = "#49483E"
foreground = "#F8F8F2"
secondary-foreground = "#A6A6A0"
accent = "#A6E22E"
hover-background = "#49483E"
pressed-background = "#5A594F"
selected-background = "#49483E"
selected-foreground = "#F8F8F2"
border = "#75715E"
focus-border = "#66D9EF"
success = "#A6E22E"
warning = "#E6DB74"
danger = "#F92672"
info = "#66D9EF"
