schema-version = 1
id = "builtin.ui.solarized-light"
name = "Solarized Light"
kind = "ui"
period = "day"
base = "builtin.ui.light"
author = "Ethan Schoonover"
source = "https://github.com/altercation/solarized"

[ui]
color-scheme = "light"
window-background = "#FDF6E3"
panel-background = "#EEE8D5"
surface-background = "#FDF6E3"
control-background = "#EEE8D5"
foreground = "#657B83"
secondary-foreground = "#839496"
disabled-foreground = "#93A1A1"
accent = "#268BD2"
hover-background = "#E5DEC8"
pressed-background = "#D8D1BC"
selected-background = "#B8DCEB"
selected-foreground = "#073642"
border = "#D3CBB7"
focus-border = "#268BD2"
success = "#859900"
warning = "#B58900"
danger = "#DC322F"
info = "#2AA198"
