//! App 根展示模型类型。

use crate::theme::ResolvedThemePalette;

use super::super::activity::ActivityViewModel;
use super::super::hosts::{
    CreateChoiceText, CreateGroupDialogViewModel, CreateHostDialogText, HostTreeViewModel,
    HostViewModel, QuickHostViewModel,
};
use super::super::palette::CommandPaletteItemViewModel;
use super::super::settings::SettingsViewModel;
use super::super::sftp::SftpViewModel;
use super::super::tabs::{SessionTabViewModel, TerminalViewModel};
use super::super::tools::{KnownHostViewModel, ToolItemViewModel};

/// Slint 窗口所需的完整展示模型。
#[derive(Debug, Clone, PartialEq, Eq)]
pub(in crate::app) struct AppViewModel {
    pub host_count: String,
    pub tab_count: String,
    pub active_page_key: &'static str,
    pub active_page: &'static str,
    pub language_label: &'static str,
    pub workspace_text: WorkspaceText,
    pub theme_name: &'static str,
    pub theme_palette: ResolvedThemePalette,
    pub background_summary: String,
    pub settings: SettingsViewModel,
    pub host_list_mode_key: &'static str,
    pub host_list_mode: &'static str,
    pub host_search_query: String,
    pub create_host_dialog_open: bool,
    pub create_group_parent_dialog_open: bool,
    pub create_group_dialog_open: bool,
    pub remove_host_dialog_open: bool,
    pub remove_host_dialog_name: String,
    pub remove_group_dialog_open: bool,
    pub remove_group_dialog_name: String,
    pub remove_group_dialog_caption: &'static str,
    pub create_host_dialog: CreateHostDialogText,
    pub create_choice: CreateChoiceText,
    pub create_group_dialog: CreateGroupDialogViewModel,
    pub quick_host: QuickHostViewModel,
    pub hosts_panel_collapsed: bool,
    pub hosts_panel_width: i32,
    pub activity_panel_width: i32,
    pub tool_panel_width: i32,
    pub tool_panel_mode_key: &'static str,
    pub tool_panel_mode: &'static str,
    pub right_sidebar_collapsed: bool,
    pub terminal: TerminalViewModel,
    pub sftp: SftpViewModel,
    pub last_error: String,
    pub command_palette_open: bool,
    pub command_palette_query: String,
    pub hosts: Vec<HostViewModel>,
    pub host_tree: Vec<HostTreeViewModel>,
    pub new_session_search_query: String,
    pub new_session_local_visible: bool,
    pub new_session_hosts: Vec<HostViewModel>,
    pub tabs: Vec<SessionTabViewModel>,
    pub activity: Vec<ActivityViewModel>,
    pub command_palette_results: Vec<CommandPaletteItemViewModel>,
    pub recent: Vec<String>,
    pub history: Vec<String>,
    pub snippets: Vec<ToolItemViewModel>,
    pub tunnels: Vec<ToolItemViewModel>,
    pub credentials: Vec<ToolItemViewModel>,
    pub known_hosts: Vec<KnownHostViewModel>,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub(in crate::app) struct WorkspaceText {
    pub brand_short: &'static str,
    pub brand_name: &'static str,
    pub topbar_find: &'static str,
    pub topbar_settings: &'static str,
    pub nav_hosts: &'static str,
    pub nav_terminal: &'static str,
    pub nav_sftp: &'static str,
    pub nav_tunnels: &'static str,
    pub nav_snippets: &'static str,
    pub nav_history: &'static str,
    pub nav_security: &'static str,
    pub nav_settings: &'static str,
    pub host_new: &'static str,
    pub host_open: &'static str,
    pub host_files: &'static str,
    pub host_edit: &'static str,
    pub host_delete: &'static str,
    pub host_duplicate: &'static str,
    pub host_delete_title: &'static str,
    pub host_delete_caption: &'static str,
    pub host_delete_confirm: &'static str,
    pub host_delete_cancel: &'static str,
    pub group_create_host: &'static str,
    pub group_create_group: &'static str,
    pub group_delete_title: &'static str,
    pub group_delete_empty_caption: &'static str,
    pub group_delete_non_empty_caption: &'static str,
    pub group_delete_confirm: &'static str,
    pub group_delete_cancel: &'static str,
    pub tool_files: &'static str,
    pub tool_snippets: &'static str,
    pub tool_history: &'static str,
    pub tool_tunnels: &'static str,
    pub tool_keys: &'static str,
    pub host_search_placeholder: &'static str,
    pub hosts_section_title: &'static str,
    pub hosts_empty_title: &'static str,
    pub hosts_empty_caption: &'static str,
    pub activity_title: &'static str,
    pub recent_title: &'static str,
    pub recent_empty: &'static str,
    pub command_palette_title: &'static str,
    pub command_palette_placeholder: &'static str,
    pub command_palette_empty: &'static str,
    pub command_palette_close: &'static str,
    pub new_session_title: &'static str,
    pub new_session_search_placeholder: &'static str,
    pub new_session_local_title: &'static str,
    pub new_session_local_subtitle: &'static str,
    pub new_session_local_detail: &'static str,
    pub new_session_local_tags: &'static str,
    pub new_session_local_status: &'static str,
    pub new_session_local_kind: &'static str,
    pub new_session_remote_kind: &'static str,
    pub new_session_ungrouped_detail: &'static str,
    pub new_session_empty_title: &'static str,
    pub new_session_empty_caption: &'static str,
    pub terminal_reconnect: &'static str,
    pub tab_ready: &'static str,
    pub sftp_loading: &'static str,
    pub sftp_split_title: &'static str,
    pub sftp_refresh: &'static str,
    pub sftp_local_title: &'static str,
    pub sftp_remote_title: &'static str,
    pub sftp_workspace_label: &'static str,
    pub sftp_queue_label: &'static str,
    pub sftp_selected_label: &'static str,
    pub sftp_path_label: &'static str,
    pub sftp_entries_label: &'static str,
    pub sftp_loading_entries: &'static str,
    pub sftp_empty_entries: &'static str,
    pub tool_pinned: &'static str,
    pub tool_empty_value: &'static str,
    pub snippets_empty: &'static str,
    pub history_commands: &'static str,
    pub history_saved_suffix: &'static str,
    pub history_empty: &'static str,
    pub history_run: &'static str,
    pub tunnels_empty: &'static str,
    pub known_hosts_empty: &'static str,
    pub known_hosts_trust: &'static str,
    pub known_hosts_delete: &'static str,
}
