//! App 根展示模型类型。

use crate::theme::ResolvedThemePalette;

use super::super::activity::ActivityViewModel;
use super::super::hosts::{
    CreateChoiceText, CreateGroupDialogViewModel, CreateHostDialogText, HostTreeViewModel,
    HostViewModel, QuickHostViewModel,
};
use super::super::palette::CommandPaletteItemViewModel;
use super::super::settings::SettingsViewModel;
use super::super::sftp::SftpViewModel;
use super::super::tabs::{SessionTabViewModel, TerminalViewModel};
use super::super::tools::{
    CredentialDetailFieldViewModel, CredentialGroupContentViewModel, CredentialRowViewModel,
    KnownHostViewModel, NetworkNavItemViewModel, SnippetRowViewModel, ToolItemViewModel,
};

/// Slint 窗口所需的完整展示模型。
#[derive(Debug, Clone, PartialEq, Eq)]
pub(in crate::app) struct AppViewModel {
    pub host_count: String,
    pub tab_count: String,
    pub active_page_key: &'static str,
    pub active_page: &'static str,
    pub language_label: &'static str,
    pub workspace_text: WorkspaceText,
    pub theme_name: &'static str,
    pub theme_palette: ResolvedThemePalette,
    pub background_summary: String,
    pub host_list_mode_key: &'static str,
    pub host_list_mode: &'static str,
    pub host_search_query: String,
    pub create_host_dialog_open: bool,
    pub create_group_parent_dialog_open: bool,
    pub create_group_dialog_open: bool,
    pub remove_host_dialog_open: bool,
    pub remove_host_dialog_name: String,
    pub remove_group_dialog_open: bool,
    pub remove_group_dialog_name: String,
    pub remove_group_dialog_caption: &'static str,
    pub create_host_dialog: CreateHostDialogText,
    pub create_choice: CreateChoiceText,
    pub create_group_dialog: CreateGroupDialogViewModel,
    pub quick_host: QuickHostViewModel,
    pub hosts_panel_collapsed: bool,
    pub hosts_panel_width: i32,
    pub activity_panel_width: i32,
    pub right_sidebar_collapsed: bool,
    pub terminal_workspace: TerminalWorkspaceViewModel,
    pub security_workspace: SecurityWorkspaceViewModel,
    pub snippet_workspace: SnippetWorkspaceViewModel,
    pub network_workspace: NetworkWorkspaceViewModel,
    pub settings_workspace: SettingsWorkspaceViewModel,
    pub last_error: String,
    pub command_palette_open: bool,
    pub command_palette_query: String,
    pub hosts: Vec<HostViewModel>,
    pub host_tree: Vec<HostTreeViewModel>,
    pub new_session_search_query: String,
    pub new_session_local_visible: bool,
    pub new_session_hosts: Vec<HostViewModel>,
    pub activity: Vec<ActivityViewModel>,
    pub command_palette_results: Vec<CommandPaletteItemViewModel>,
    pub recent: Vec<String>,
}

/// 终端页和右侧工具面板需要的 Rust 侧页面模型。
#[derive(Debug, Clone, PartialEq, Eq)]
pub(in crate::app) struct TerminalWorkspaceViewModel {
    pub terminal: TerminalViewModel,
    pub sftp: SftpViewModel,
    pub tabs: Vec<SessionTabViewModel>,
    pub history: Vec<String>,
    pub tunnels: Vec<ToolItemViewModel>,
    pub known_hosts: Vec<KnownHostViewModel>,
    pub tool_panel_width: i32,
    pub tool_panel_mode_key: &'static str,
    pub tool_panel_mode: &'static str,
}

/// 凭据页需要的 Rust 侧页面模型。
#[derive(Debug, Clone, PartialEq, Eq)]
pub(in crate::app) struct SecurityWorkspaceViewModel {
    pub search_query: String,
    pub credentials: Vec<ToolItemViewModel>,
    pub credential_rows: Vec<CredentialRowViewModel>,
    pub group_contents: Vec<CredentialGroupContentViewModel>,
    pub detail_fields: Vec<CredentialDetailFieldViewModel>,
}

/// 片段页需要的 Rust 侧页面模型。
#[derive(Debug, Clone, PartialEq, Eq)]
pub(in crate::app) struct SnippetWorkspaceViewModel {
    pub search_query: String,
    pub snippets: Vec<ToolItemViewModel>,
    pub rows: Vec<SnippetRowViewModel>,
    pub target_options: Vec<SnippetRowViewModel>,
}

/// Network 页需要的 Rust 侧页面模型。
#[derive(Debug, Clone, PartialEq, Eq)]
pub(in crate::app) struct NetworkWorkspaceViewModel {
    pub runtime_tunnels: Vec<NetworkNavItemViewModel>,
    pub resources: Vec<NetworkNavItemViewModel>,
}

/// 设置页需要的 Rust 侧页面模型。
#[derive(Debug, Clone, PartialEq, Eq)]
pub(in crate::app) struct SettingsWorkspaceViewModel {
    pub settings: SettingsViewModel,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub(in crate::app) struct WorkspaceText {
    pub brand_short: &'static str,
    pub brand_name: &'static str,
    pub topbar_find: &'static str,
    pub topbar_settings: &'static str,
    pub nav_hosts: &'static str,
    pub nav_terminal: &'static str,
    pub nav_sftp: &'static str,
    pub nav_tunnels: &'static str,
    pub nav_snippets: &'static str,
    pub nav_history: &'static str,
    pub nav_security: &'static str,
    pub nav_proxy: &'static str,
    pub nav_settings: &'static str,
    pub host_new: &'static str,
    pub host_open: &'static str,
    pub host_files: &'static str,
    pub host_edit: &'static str,
    pub host_delete: &'static str,
    pub host_duplicate: &'static str,
    pub host_delete_title: &'static str,
    pub host_delete_caption: &'static str,
    pub host_delete_confirm: &'static str,
    pub host_delete_cancel: &'static str,
    pub group_create_host: &'static str,
    pub group_create_group: &'static str,
    pub group_delete_title: &'static str,
    pub group_delete_empty_caption: &'static str,
    pub group_delete_non_empty_caption: &'static str,
    pub group_delete_confirm: &'static str,
    pub group_delete_cancel: &'static str,
    pub tool_files: &'static str,
    pub tool_snippets: &'static str,
    pub tool_history: &'static str,
    pub tool_tunnels: &'static str,
    pub tool_keys: &'static str,
    pub tool_proxy: &'static str,
    pub proxy_empty: &'static str,
    pub proxy_section_route: &'static str,
    pub proxy_section_forward: &'static str,
    pub proxy_section_host: &'static str,
    pub proxy_jump_caption: &'static str,
    pub proxy_command_caption: &'static str,
    pub proxy_forward_caption: &'static str,
    pub proxy_host_hint_caption: &'static str,
    pub proxy_runtime_section: &'static str,
    pub proxy_resources_section: &'static str,
    pub proxy_runtime_empty: &'static str,
    pub proxy_resources_empty: &'static str,
    pub proxy_new_proxy: &'static str,
    pub proxy_new_jump: &'static str,
    pub proxy_new_forward: &'static str,
    pub proxy_edit: &'static str,
    pub proxy_delete: &'static str,
    pub proxy_save: &'static str,
    pub proxy_cancel: &'static str,
    pub proxy_delete_title: &'static str,
    pub proxy_delete_caption: &'static str,
    pub proxy_name_label: &'static str,
    pub proxy_name_placeholder: &'static str,
    pub proxy_address_label: &'static str,
    pub proxy_port_label: &'static str,
    pub proxy_tags_label: &'static str,
    pub proxy_bind_label: &'static str,
    pub proxy_target_label: &'static str,
    pub proxy_host_ids_label: &'static str,
    pub proxy_host_ids_placeholder: &'static str,
    pub proxy_bind_host_placeholder: &'static str,
    pub proxy_target_host_placeholder: &'static str,
    pub proxy_tags_placeholder: &'static str,
    pub proxy_auto_start: &'static str,
    pub proxy_kind_socks5: &'static str,
    pub proxy_kind_http: &'static str,
    pub proxy_kind_local: &'static str,
    pub proxy_kind_remote: &'static str,
    pub proxy_kind_dynamic: &'static str,
    pub security_tree_title: &'static str,
    pub security_search_placeholder: &'static str,
    pub security_new: &'static str,
    pub security_create_action_title: &'static str,
    pub security_create_action_create: &'static str,
    pub security_create_action_create_caption: &'static str,
    pub security_create_action_import: &'static str,
    pub security_create_action_import_caption: &'static str,
    pub security_create_action_group_caption: &'static str,
    pub security_create_type_title: &'static str,
    pub security_create_type_create_caption: &'static str,
    pub security_create_type_import_caption: &'static str,
    pub security_group_new: &'static str,
    pub security_group_edit: &'static str,
    pub security_group_delete: &'static str,
    pub security_private_keys: &'static str,
    pub security_certificates: &'static str,
    pub security_passwords: &'static str,
    pub security_agents: &'static str,
    pub security_private_key_create: &'static str,
    pub security_private_key_import: &'static str,
    pub security_certificate_create: &'static str,
    pub security_certificate_import: &'static str,
    pub security_password_create: &'static str,
    pub security_agent_create: &'static str,
    pub security_private_key_create_title: &'static str,
    pub security_private_key_import_title: &'static str,
    pub security_certificate_create_title: &'static str,
    pub security_certificate_import_title: &'static str,
    pub security_password_create_title: &'static str,
    pub security_agent_create_title: &'static str,
    pub security_credential_name_label: &'static str,
    pub security_credential_name_placeholder: &'static str,
    pub security_credential_secret_label: &'static str,
    pub security_private_key_secret_placeholder: &'static str,
    pub security_certificate_secret_placeholder: &'static str,
    pub security_password_secret_label: &'static str,
    pub security_password_secret_placeholder: &'static str,
    pub security_password_show: &'static str,
    pub security_password_hide: &'static str,
    pub security_agent_secret_label: &'static str,
    pub security_agent_secret_placeholder: &'static str,
    pub security_private_key_source_label: &'static str,
    pub security_private_key_source_placeholder: &'static str,
    pub security_private_key_import_file: &'static str,
    pub security_private_key_import_text: &'static str,
    pub security_private_key_text_label: &'static str,
    pub security_private_key_text_placeholder: &'static str,
    pub security_certificate_source_label: &'static str,
    pub security_certificate_source_placeholder: &'static str,
    pub security_certificate_text_label: &'static str,
    pub security_certificate_text_placeholder: &'static str,
    pub security_certificate_ca_key_label: &'static str,
    pub security_certificate_ca_key_placeholder: &'static str,
    pub security_certificate_subject_key_label: &'static str,
    pub security_certificate_subject_key_placeholder: &'static str,
    pub security_certificate_type_label: &'static str,
    pub security_certificate_type_user: &'static str,
    pub security_certificate_type_host: &'static str,
    pub security_certificate_principals_label: &'static str,
    pub security_certificate_principals_placeholder: &'static str,
    pub security_certificate_valid_days_label: &'static str,
    pub security_certificate_valid_days_placeholder: &'static str,
    pub security_certificate_key_id_label: &'static str,
    pub security_certificate_key_id_placeholder: &'static str,
    pub security_certificate_serial_label: &'static str,
    pub security_certificate_serial_placeholder: &'static str,
    pub security_certificate_key_picker_title: &'static str,
    pub security_certificate_empty_private_keys: &'static str,
    pub security_credential_algorithm_label: &'static str,
    pub security_credential_save: &'static str,
    pub security_credential_generating_private_key: &'static str,
    pub security_credential_edit: &'static str,
    pub security_credential_edit_private_key: &'static str,
    pub security_credential_edit_certificate: &'static str,
    pub security_credential_edit_password: &'static str,
    pub security_credential_move: &'static str,
    pub security_credential_duplicate: &'static str,
    pub security_credential_export: &'static str,
    pub security_credential_replace_secret: &'static str,
    pub security_credential_delete: &'static str,
    pub security_credential_delete_title: &'static str,
    pub security_credential_delete_caption: &'static str,
    pub security_credential_delete_confirm: &'static str,
    pub security_credential_delete_cancel: &'static str,
    pub security_credential_export_title: &'static str,
    pub security_credential_export_path_label: &'static str,
    pub security_credential_export_path_placeholder: &'static str,
    pub security_credential_replace_secret_title: &'static str,
    pub security_credential_replace_secret_label: &'static str,
    pub security_credential_replace_secret_placeholder: &'static str,
    pub security_credential_replace_secret_confirm_title: &'static str,
    pub security_credential_replace_secret_confirm_caption: &'static str,
    pub security_credential_replace_secret_confirm: &'static str,
    pub security_view_content: &'static str,
    pub security_view_private_key: &'static str,
    pub security_view_certificate: &'static str,
    pub security_view_password: &'static str,
    pub security_secret_copy: &'static str,
    pub security_secret_copy_success: &'static str,
    pub security_secret_copy_failed: &'static str,
    pub security_secret_content_missing: &'static str,
    pub security_detail_empty_title: &'static str,
    pub security_detail_empty_caption: &'static str,
    pub security_field_type: &'static str,
    pub security_field_username: &'static str,
    pub security_field_algorithm: &'static str,
    pub security_field_fingerprint: &'static str,
    pub security_field_secret_ref: &'static str,
    pub security_field_group: &'static str,
    pub security_group_caption: &'static str,
    pub host_search_placeholder: &'static str,
    pub hosts_section_title: &'static str,
    pub hosts_empty_title: &'static str,
    pub hosts_empty_caption: &'static str,
    pub activity_title: &'static str,
    pub recent_title: &'static str,
    pub recent_empty: &'static str,
    pub command_palette_title: &'static str,
    pub command_palette_placeholder: &'static str,
    pub command_palette_empty: &'static str,
    pub command_palette_close: &'static str,
    pub new_session_title: &'static str,
    pub new_session_search_placeholder: &'static str,
    pub new_session_local_title: &'static str,
    pub new_session_local_subtitle: &'static str,
    pub new_session_local_detail: &'static str,
    pub new_session_local_tags: &'static str,
    pub new_session_local_status: &'static str,
    pub new_session_local_kind: &'static str,
    pub new_session_remote_kind: &'static str,
    pub new_session_ungrouped_detail: &'static str,
    pub new_session_empty_title: &'static str,
    pub new_session_empty_caption: &'static str,
    pub terminal_reconnect: &'static str,
    pub tab_ready: &'static str,
    pub sftp_loading: &'static str,
    pub sftp_split_title: &'static str,
    pub sftp_refresh: &'static str,
    pub sftp_local_title: &'static str,
    pub sftp_remote_title: &'static str,
    pub sftp_workspace_label: &'static str,
    pub sftp_queue_label: &'static str,
    pub sftp_selected_label: &'static str,
    pub sftp_path_label: &'static str,
    pub sftp_entries_label: &'static str,
    pub sftp_loading_entries: &'static str,
    pub sftp_empty_entries: &'static str,
    pub tool_pinned: &'static str,
    pub tool_empty_value: &'static str,
    pub snippets_tree_title: &'static str,
    pub snippets_search_placeholder: &'static str,
    pub snippets_detail_empty_title: &'static str,
    pub snippets_detail_empty_caption: &'static str,
    pub snippets_field_scope: &'static str,
    pub snippets_field_variables: &'static str,
    pub snippets_field_arguments: &'static str,
    pub snippets_command_template: &'static str,
    pub snippets_group_caption: &'static str,
    pub snippets_description_empty: &'static str,
    pub snippets_new: &'static str,
    pub snippets_new_snippet: &'static str,
    pub snippets_new_snippet_caption: &'static str,
    pub snippets_new_target: &'static str,
    pub snippets_new_group: &'static str,
    pub snippets_new_group_caption: &'static str,
    pub snippets_create_choice_title: &'static str,
    pub snippets_group_contents_title: &'static str,
    pub snippets_target_variant_title: &'static str,
    pub snippets_script_relation: &'static str,
    pub snippets_script_shared: &'static str,
    pub snippets_script_independent: &'static str,
    pub snippets_create_snippet_title: &'static str,
    pub snippets_create_target_title: &'static str,
    pub snippets_create_group_title: &'static str,
    pub snippets_edit_snippet_title: &'static str,
    pub snippets_edit_target_title: &'static str,
    pub snippets_edit_group_title: &'static str,
    pub snippets_edit: &'static str,
    pub snippets_delete: &'static str,
    pub snippets_delete_title: &'static str,
    pub snippets_delete_snippet_caption: &'static str,
    pub snippets_delete_group_caption: &'static str,
    pub snippets_delete_target_caption: &'static str,
    pub snippets_delete_confirm: &'static str,
    pub snippets_copy: &'static str,
    pub snippets_copy_success: &'static str,
    pub snippets_copy_failed: &'static str,
    pub snippets_run: &'static str,
    pub snippets_run_title: &'static str,
    pub snippets_run_host_label: &'static str,
    pub snippets_run_arguments_label: &'static str,
    pub snippets_run_arguments_placeholder: &'static str,
    pub snippets_run_no_hosts: &'static str,
    pub snippets_move: &'static str,
    pub snippets_move_title: &'static str,
    pub snippets_move_root: &'static str,
    pub snippets_choose_group: &'static str,
    pub snippets_confirm_group: &'static str,
    pub snippets_name_label: &'static str,
    pub snippets_name_placeholder: &'static str,
    pub snippets_group_name_placeholder: &'static str,
    pub snippets_description_label: &'static str,
    pub snippets_description_placeholder: &'static str,
    pub snippets_target_key_label: &'static str,
    pub snippets_target_key_placeholder: &'static str,
    pub snippets_target_picker_placeholder: &'static str,
    pub snippets_target_linux: &'static str,
    pub snippets_target_debian: &'static str,
    pub snippets_target_rhel: &'static str,
    pub snippets_target_alpine: &'static str,
    pub snippets_target_fedora: &'static str,
    pub snippets_target_arch: &'static str,
    pub snippets_target_suse: &'static str,
    pub snippets_target_freebsd: &'static str,
    pub snippets_target_macos: &'static str,
    pub snippets_target_powershell: &'static str,
    pub snippets_target_cmd: &'static str,
    pub snippets_command_placeholder: &'static str,
    pub snippets_target_mode_new: &'static str,
    pub snippets_target_mode_new_caption: &'static str,
    pub snippets_target_mode_share: &'static str,
    pub snippets_target_mode_share_caption: &'static str,
    pub snippets_shared_target: &'static str,
    pub snippets_split_target: &'static str,
    pub snippets_cancel: &'static str,
    pub snippets_create: &'static str,
    pub snippets_save: &'static str,
    pub snippets_empty: &'static str,
    pub history_commands: &'static str,
    pub history_saved_suffix: &'static str,
    pub history_empty: &'static str,
    pub history_run: &'static str,
    pub tunnels_empty: &'static str,
    pub known_hosts_empty: &'static str,
    pub known_hosts_trust: &'static str,
    pub known_hosts_delete: &'static str,
}
