//! 工作区静态文案展示模型。
//!
//! 这个模块只负责把 i18n key 投影到 `WorkspaceText`。根构建器只负责组合各类
//! view model，不再承载几百行文案映射。

use crate::model::AppState;

use super::super::i18n::{locale_for_state, tr};
use super::types::WorkspaceText;

pub(super) fn workspace_text(state: &AppState) -> WorkspaceText {
    let locale = locale_for_state(state);

    WorkspaceText {
        brand_short: tr(locale, "brand.short"),
        brand_name: tr(locale, "brand.name"),
        topbar_find: tr(locale, "topbar.find"),
        topbar_settings: tr(locale, "topbar.settings"),
        nav_hosts: tr(locale, "nav.hosts"),
        nav_terminal: tr(locale, "nav.terminal"),
        nav_sftp: tr(locale, "nav.sftp"),
        nav_tunnels: tr(locale, "nav.tunnels"),
        nav_snippets: tr(locale, "nav.snippets"),
        nav_history: tr(locale, "nav.history"),
        nav_security: tr(locale, "nav.security"),
        nav_proxy: tr(locale, "nav.proxy"),
        nav_settings: tr(locale, "nav.settings"),
        host_new: tr(locale, "host.new"),
        host_open: tr(locale, "host.open"),
        host_files: tr(locale, "host.files"),
        host_edit: tr(locale, "host.edit"),
        host_delete: tr(locale, "host.delete"),
        host_duplicate: tr(locale, "host.duplicate"),
        host_delete_title: tr(locale, "host.delete_title"),
        host_delete_caption: tr(locale, "host.delete_caption"),
        host_delete_confirm: tr(locale, "host.delete_confirm"),
        host_delete_cancel: tr(locale, "host.delete_cancel"),
        group_create_host: tr(locale, "group.create_host"),
        group_create_group: tr(locale, "group.create_group"),
        group_delete_title: tr(locale, "group.delete_title"),
        group_delete_empty_caption: tr(locale, "group.delete_empty_caption"),
        group_delete_non_empty_caption: tr(locale, "group.delete_non_empty_caption"),
        group_delete_confirm: tr(locale, "group.delete_confirm"),
        group_delete_cancel: tr(locale, "group.delete_cancel"),
        tool_files: tr(locale, "tool.files"),
        tool_snippets: tr(locale, "tool.snippets"),
        tool_history: tr(locale, "tool.history"),
        tool_tunnels: tr(locale, "tool.tunnels"),
        tool_keys: tr(locale, "tool.keys"),
        tool_proxy: tr(locale, "tool.proxy"),
        proxy_empty: tr(locale, "tool.proxy_empty"),
        security_tree_title: tr(locale, "security.tree_title"),
        security_search_placeholder: tr(locale, "security.search_placeholder"),
        security_new: tr(locale, "security.new"),
        security_create_action_title: tr(locale, "security.create_action_title"),
        security_create_action_create: tr(locale, "security.create_action_create"),
        security_create_action_create_caption: tr(locale, "security.create_action_create_caption"),
        security_create_action_import: tr(locale, "security.create_action_import"),
        security_create_action_import_caption: tr(locale, "security.create_action_import_caption"),
        security_create_action_group_caption: tr(locale, "security.create_action_group_caption"),
        security_create_type_title: tr(locale, "security.create_type_title"),
        security_create_type_create_caption: tr(locale, "security.create_type_create_caption"),
        security_create_type_import_caption: tr(locale, "security.create_type_import_caption"),
        security_group_new: tr(locale, "security.group_new"),
        security_group_edit: tr(locale, "security.group_edit"),
        security_group_delete: tr(locale, "security.group_delete"),
        security_private_keys: tr(locale, "security.private_keys"),
        security_certificates: tr(locale, "security.certificates"),
        security_passwords: tr(locale, "security.passwords"),
        security_agents: tr(locale, "security.agents"),
        security_private_key_create: tr(locale, "security.private_key_create"),
        security_private_key_import: tr(locale, "security.private_key_import"),
        security_certificate_create: tr(locale, "security.certificate_create"),
        security_certificate_import: tr(locale, "security.certificate_import"),
        security_password_create: tr(locale, "security.password_create"),
        security_agent_create: tr(locale, "security.agent_create"),
        security_private_key_create_title: tr(locale, "security.private_key_create_title"),
        security_private_key_import_title: tr(locale, "security.private_key_import_title"),
        security_certificate_create_title: tr(locale, "security.certificate_create_title"),
        security_certificate_import_title: tr(locale, "security.certificate_import_title"),
        security_password_create_title: tr(locale, "security.password_create_title"),
        security_agent_create_title: tr(locale, "security.agent_create_title"),
        security_credential_name_label: tr(locale, "security.credential_name_label"),
        security_credential_name_placeholder: tr(locale, "security.credential_name_placeholder"),
        security_credential_secret_label: tr(locale, "security.credential_secret_label"),
        security_private_key_secret_placeholder: tr(
            locale,
            "security.private_key_secret_placeholder",
        ),
        security_certificate_secret_placeholder: tr(
            locale,
            "security.certificate_secret_placeholder",
        ),
        security_password_secret_label: tr(locale, "security.password_secret_label"),
        security_password_secret_placeholder: tr(locale, "security.password_secret_placeholder"),
        security_password_show: tr(locale, "security.password_show"),
        security_password_hide: tr(locale, "security.password_hide"),
        security_agent_secret_label: tr(locale, "security.agent_secret_label"),
        security_agent_secret_placeholder: tr(locale, "security.agent_secret_placeholder"),
        security_private_key_source_label: tr(locale, "security.private_key_source_label"),
        security_private_key_source_placeholder: tr(
            locale,
            "security.private_key_source_placeholder",
        ),
        security_private_key_import_file: tr(locale, "security.private_key_import_file"),
        security_private_key_import_text: tr(locale, "security.private_key_import_text"),
        security_private_key_text_label: tr(locale, "security.private_key_text_label"),
        security_private_key_text_placeholder: tr(locale, "security.private_key_text_placeholder"),
        security_certificate_source_label: tr(locale, "security.certificate_source_label"),
        security_certificate_source_placeholder: tr(
            locale,
            "security.certificate_source_placeholder",
        ),
        security_certificate_text_label: tr(locale, "security.certificate_text_label"),
        security_certificate_text_placeholder: tr(locale, "security.certificate_text_placeholder"),
        security_certificate_ca_key_label: tr(locale, "security.certificate_ca_key_label"),
        security_certificate_ca_key_placeholder: tr(
            locale,
            "security.certificate_ca_key_placeholder",
        ),
        security_certificate_subject_key_label: tr(
            locale,
            "security.certificate_subject_key_label",
        ),
        security_certificate_subject_key_placeholder: tr(
            locale,
            "security.certificate_subject_key_placeholder",
        ),
        security_certificate_type_label: tr(locale, "security.certificate_type_label"),
        security_certificate_type_user: tr(locale, "security.certificate_type_user"),
        security_certificate_type_host: tr(locale, "security.certificate_type_host"),
        security_certificate_principals_label: tr(locale, "security.certificate_principals_label"),
        security_certificate_principals_placeholder: tr(
            locale,
            "security.certificate_principals_placeholder",
        ),
        security_certificate_valid_days_label: tr(locale, "security.certificate_valid_days_label"),
        security_certificate_valid_days_placeholder: tr(
            locale,
            "security.certificate_valid_days_placeholder",
        ),
        security_certificate_key_id_label: tr(locale, "security.certificate_key_id_label"),
        security_certificate_key_id_placeholder: tr(
            locale,
            "security.certificate_key_id_placeholder",
        ),
        security_certificate_serial_label: tr(locale, "security.certificate_serial_label"),
        security_certificate_serial_placeholder: tr(
            locale,
            "security.certificate_serial_placeholder",
        ),
        security_certificate_key_picker_title: tr(locale, "security.certificate_key_picker_title"),
        security_certificate_empty_private_keys: tr(
            locale,
            "security.certificate_empty_private_keys",
        ),
        security_credential_algorithm_label: tr(locale, "security.credential_algorithm_label"),
        security_credential_save: tr(locale, "security.credential_save"),
        security_credential_generating_private_key: tr(
            locale,
            "security.credential_generating_private_key",
        ),
        security_credential_edit: tr(locale, "security.credential_edit"),
        security_credential_edit_private_key: tr(locale, "security.credential_edit_private_key"),
        security_credential_edit_certificate: tr(locale, "security.credential_edit_certificate"),
        security_credential_edit_password: tr(locale, "security.credential_edit_password"),
        security_credential_move: tr(locale, "security.credential_move"),
        security_credential_duplicate: tr(locale, "security.credential_duplicate"),
        security_credential_export: tr(locale, "security.credential_export"),
        security_credential_replace_secret: tr(locale, "security.credential_replace_secret"),
        security_credential_delete: tr(locale, "security.credential_delete"),
        security_credential_delete_title: tr(locale, "security.credential_delete_title"),
        security_credential_delete_caption: tr(locale, "security.credential_delete_caption"),
        security_credential_delete_confirm: tr(locale, "security.credential_delete_confirm"),
        security_credential_delete_cancel: tr(locale, "security.credential_delete_cancel"),
        security_credential_export_title: tr(locale, "security.credential_export_title"),
        security_credential_export_path_label: tr(locale, "security.credential_export_path_label"),
        security_credential_export_path_placeholder: tr(
            locale,
            "security.credential_export_path_placeholder",
        ),
        security_credential_replace_secret_title: tr(
            locale,
            "security.credential_replace_secret_title",
        ),
        security_credential_replace_secret_label: tr(
            locale,
            "security.credential_replace_secret_label",
        ),
        security_credential_replace_secret_placeholder: tr(
            locale,
            "security.credential_replace_secret_placeholder",
        ),
        security_credential_replace_secret_confirm_title: tr(
            locale,
            "security.credential_replace_secret_confirm_title",
        ),
        security_credential_replace_secret_confirm_caption: tr(
            locale,
            "security.credential_replace_secret_confirm_caption",
        ),
        security_credential_replace_secret_confirm: tr(
            locale,
            "security.credential_replace_secret_confirm",
        ),
        security_view_content: tr(locale, "security.view_content"),
        security_view_private_key: tr(locale, "security.view_private_key"),
        security_view_certificate: tr(locale, "security.view_certificate"),
        security_view_password: tr(locale, "security.view_password"),
        security_secret_copy: tr(locale, "security.secret_copy"),
        security_secret_copy_success: tr(locale, "security.secret_copy_success"),
        security_secret_copy_failed: tr(locale, "security.secret_copy_failed"),
        security_secret_content_missing: tr(locale, "security.secret_content_missing"),
        security_detail_empty_title: tr(locale, "security.detail_empty_title"),
        security_detail_empty_caption: tr(locale, "security.detail_empty_caption"),
        security_field_type: tr(locale, "security.field_type"),
        security_field_username: tr(locale, "security.field_username"),
        security_field_algorithm: tr(locale, "security.field_algorithm"),
        security_field_fingerprint: tr(locale, "security.field_fingerprint"),
        security_field_secret_ref: tr(locale, "security.field_secret_ref"),
        security_field_group: tr(locale, "security.field_group"),
        security_group_caption: tr(locale, "security.group_caption"),
        host_search_placeholder: tr(locale, "host.search_placeholder"),
        hosts_section_title: tr(locale, "host.section_title"),
        hosts_empty_title: tr(locale, "host.empty_title"),
        hosts_empty_caption: tr(locale, "host.empty_caption"),
        activity_title: tr(locale, "activity.title"),
        recent_title: tr(locale, "activity.recent_title"),
        recent_empty: tr(locale, "activity.recent_empty"),
        command_palette_title: tr(locale, "palette.title"),
        command_palette_placeholder: tr(locale, "palette.placeholder"),
        command_palette_empty: tr(locale, "palette.empty"),
        command_palette_close: tr(locale, "palette.close"),
        new_session_title: tr(locale, "new_session.title"),
        new_session_search_placeholder: tr(locale, "new_session.search_placeholder"),
        new_session_local_title: tr(locale, "new_session.local_title"),
        new_session_local_subtitle: tr(locale, "new_session.local_subtitle"),
        new_session_local_detail: tr(locale, "new_session.local_detail"),
        new_session_local_tags: tr(locale, "new_session.local_tags"),
        new_session_local_status: tr(locale, "new_session.local_status"),
        new_session_local_kind: tr(locale, "new_session.local_kind"),
        new_session_remote_kind: tr(locale, "new_session.remote_kind"),
        new_session_ungrouped_detail: tr(locale, "new_session.ungrouped_detail"),
        new_session_empty_title: tr(locale, "new_session.empty_title"),
        new_session_empty_caption: tr(locale, "new_session.empty_caption"),
        terminal_reconnect: tr(locale, "terminal.reconnect"),
        tab_ready: tr(locale, "tab.ready"),
        sftp_loading: tr(locale, "sftp.loading"),
        sftp_split_title: tr(locale, "sftp.split_title"),
        sftp_refresh: tr(locale, "sftp.refresh"),
        sftp_local_title: tr(locale, "sftp.local_title"),
        sftp_remote_title: tr(locale, "sftp.remote_title"),
        sftp_workspace_label: tr(locale, "sftp.workspace"),
        sftp_queue_label: tr(locale, "sftp.queue"),
        sftp_selected_label: tr(locale, "sftp.selected"),
        sftp_path_label: tr(locale, "sftp.path"),
        sftp_entries_label: tr(locale, "sftp.entries"),
        sftp_loading_entries: tr(locale, "sftp.loading_entries"),
        sftp_empty_entries: tr(locale, "sftp.empty_entries"),
        tool_pinned: tr(locale, "tool.pinned"),
        tool_empty_value: tr(locale, "tool.empty_value"),
        snippets_tree_title: tr(locale, "snippets.tree_title"),
        snippets_search_placeholder: tr(locale, "snippets.search_placeholder"),
        snippets_detail_empty_title: tr(locale, "snippets.detail_empty_title"),
        snippets_detail_empty_caption: tr(locale, "snippets.detail_empty_caption"),
        snippets_field_scope: tr(locale, "snippets.field_scope"),
        snippets_field_variables: tr(locale, "snippets.field_variables"),
        snippets_field_arguments: tr(locale, "snippets.field_arguments"),
        snippets_command_template: tr(locale, "snippets.command_template"),
        snippets_group_caption: tr(locale, "snippets.group_caption"),
        snippets_description_empty: tr(locale, "snippets.description_empty"),
        snippets_new: tr(locale, "snippets.new"),
        snippets_new_snippet: tr(locale, "snippets.new_snippet"),
        snippets_new_snippet_caption: tr(locale, "snippets.new_snippet_caption"),
        snippets_new_target: tr(locale, "snippets.new_target"),
        snippets_new_group: tr(locale, "snippets.new_group"),
        snippets_new_group_caption: tr(locale, "snippets.new_group_caption"),
        snippets_create_choice_title: tr(locale, "snippets.create_choice_title"),
        snippets_group_contents_title: tr(locale, "snippets.group_contents_title"),
        snippets_target_variant_title: tr(locale, "snippets.target_variant_title"),
        snippets_script_relation: tr(locale, "snippets.script_relation"),
        snippets_script_shared: tr(locale, "snippets.script_shared"),
        snippets_script_independent: tr(locale, "snippets.script_independent"),
        snippets_create_snippet_title: tr(locale, "snippets.create_snippet_title"),
        snippets_create_target_title: tr(locale, "snippets.create_target_title"),
        snippets_create_group_title: tr(locale, "snippets.create_group_title"),
        snippets_edit_snippet_title: tr(locale, "snippets.edit_snippet_title"),
        snippets_edit_target_title: tr(locale, "snippets.edit_target_title"),
        snippets_edit_group_title: tr(locale, "snippets.edit_group_title"),
        snippets_edit: tr(locale, "snippets.edit"),
        snippets_delete: tr(locale, "snippets.delete"),
        snippets_delete_title: tr(locale, "snippets.delete_title"),
        snippets_delete_snippet_caption: tr(locale, "snippets.delete_snippet_caption"),
        snippets_delete_group_caption: tr(locale, "snippets.delete_group_caption"),
        snippets_delete_target_caption: tr(locale, "snippets.delete_target_caption"),
        snippets_delete_confirm: tr(locale, "snippets.delete_confirm"),
        snippets_copy: tr(locale, "snippets.copy"),
        snippets_copy_success: tr(locale, "snippets.copy_success"),
        snippets_copy_failed: tr(locale, "snippets.copy_failed"),
        snippets_run: tr(locale, "snippets.run"),
        snippets_run_title: tr(locale, "snippets.run_title"),
        snippets_run_host_label: tr(locale, "snippets.run_host_label"),
        snippets_run_arguments_label: tr(locale, "snippets.run_arguments_label"),
        snippets_run_arguments_placeholder: tr(locale, "snippets.run_arguments_placeholder"),
        snippets_run_no_hosts: tr(locale, "snippets.run_no_hosts"),
        snippets_move: tr(locale, "snippets.move"),
        snippets_move_title: tr(locale, "snippets.move_title"),
        snippets_move_root: tr(locale, "snippets.move_root"),
        snippets_name_label: tr(locale, "snippets.name_label"),
        snippets_name_placeholder: tr(locale, "snippets.name_placeholder"),
        snippets_group_name_placeholder: tr(locale, "snippets.group_name_placeholder"),
        snippets_description_label: tr(locale, "snippets.description_label"),
        snippets_description_placeholder: tr(locale, "snippets.description_placeholder"),
        snippets_target_key_label: tr(locale, "snippets.target_key_label"),
        snippets_target_key_placeholder: tr(locale, "snippets.target_key_placeholder"),
        snippets_target_picker_placeholder: tr(locale, "snippets.target_picker_placeholder"),
        snippets_target_linux: tr(locale, "snippets.target_linux"),
        snippets_target_debian: tr(locale, "snippets.target_debian"),
        snippets_target_rhel: tr(locale, "snippets.target_rhel"),
        snippets_target_macos: tr(locale, "snippets.target_macos"),
        snippets_target_powershell: tr(locale, "snippets.target_powershell"),
        snippets_target_cmd: tr(locale, "snippets.target_cmd"),
        snippets_command_placeholder: tr(locale, "snippets.command_placeholder"),
        snippets_target_mode_new: tr(locale, "snippets.target_mode_new"),
        snippets_target_mode_new_caption: tr(locale, "snippets.target_mode_new_caption"),
        snippets_target_mode_share: tr(locale, "snippets.target_mode_share"),
        snippets_target_mode_share_caption: tr(locale, "snippets.target_mode_share_caption"),
        snippets_shared_target: tr(locale, "snippets.shared_target"),
        snippets_split_target: tr(locale, "snippets.split_target"),
        snippets_cancel: tr(locale, "snippets.cancel"),
        snippets_create: tr(locale, "snippets.create"),
        snippets_save: tr(locale, "snippets.save"),
        snippets_empty: tr(locale, "tool.snippets_empty"),
        history_commands: tr(locale, "tool.history_commands"),
        history_saved_suffix: tr(locale, "tool.history_saved_suffix"),
        history_empty: tr(locale, "tool.history_empty"),
        history_run: tr(locale, "tool.history_run"),
        tunnels_empty: tr(locale, "tool.tunnels_empty"),
        known_hosts_empty: tr(locale, "tool.known_hosts_empty"),
        known_hosts_trust: tr(locale, "tool.known_hosts_trust"),
        known_hosts_delete: tr(locale, "tool.known_hosts_delete"),
    }
}
