[package]
name = "smagical-ui-kernel"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
authors.workspace = true
build = "build.rs"

[dependencies]
slint.workspace = true
smagical-ui-common = { path = "../common" }
plugin-hosts = { path = "../plugins/hosts" }
plugin-credentials = { path = "../plugins/credentials" }
plugin-files = { path = "../plugins/files" }
plugin-history = { path = "../plugins/history" }
plugin-snippets = { path = "../plugins/snippets" }
plugin-tunnels = { path = "../plugins/tunnels" }
plugin-debug = { path = "../plugins/debug" }
plugin-settings = { path = "../plugins/settings" }

[lib]
test = false
doctest = false
bench = false

[build-dependencies]
slint-build.workspace = true
