schema-version = 1
id = "builtin.terminal.monokai"
name = "Monokai"
kind = "terminal"
author = "Monokai"
source = "https://monokai.pro"
[terminal]
background = "#272822"
foreground = "#F8F8F2"
cursorColor = "#F8F8F0"
selectionBackground = "#49483E"
black = "#272822"
red = "#F92672"
green = "#A6E22E"
yellow = "#E6DB74"
blue = "#66D9EF"
purple = "#AE81FF"
cyan = "#A1EFE4"
white = "#F8F8F2"
brightBlack = "#75715E"
brightRed = "#F92672"
brightGreen = "#A6E22E"
brightYellow = "#E6DB74"
brightBlue = "#66D9EF"
brightPurple = "#AE81FF"
brightCyan = "#A1EFE4"
brightWhite = "#F9F8F5"
