schema-version = 1
id = "builtin.terminal.catppuccin-latte"
name = "Catppuccin Latte"
kind = "terminal"
author = "Catppuccin"
source = "https://github.com/catppuccin/catppuccin"
[terminal]
background = "#EFF1F5"
foreground = "#4C4F69"
cursorColor = "#1E66F5"
selectionBackground = "#BFD7FF"
black = "#5C5F77"
red = "#D20F39"
green = "#40A02B"
yellow = "#DF8E1D"
blue = "#1E66F5"
purple = "#8839EF"
cyan = "#179299"
white = "#ACB0BE"
brightBlack = "#6C6F85"
brightRed = "#D20F39"
brightGreen = "#40A02B"
brightYellow = "#DF8E1D"
brightBlue = "#1E66F5"
brightPurple = "#8839EF"
brightCyan = "#179299"
brightWhite = "#BCC0CC"
