schema-version = 1
id = "builtin.terminal.github-light"
name = "GitHub Light"
kind = "terminal"
author = "GitHub Primer"
source = "https://github.com/primer/primitives"
[terminal]
background = "#FFFFFF"
foreground = "#24292F"
cursorColor = "#0969DA"
selectionBackground = "#B6E3FF"
black = "#24292F"
red = "#CF222E"
green = "#1A7F37"
yellow = "#9A6700"
blue = "#0969DA"
purple = "#8250DF"
cyan = "#1B7C83"
white = "#FFFFFF"
brightBlack = "#57606A"
brightRed = "#A40E26"
brightGreen = "#116329"
brightYellow = "#7D4E00"
brightBlue = "#0550AE"
brightPurple = "#6639BA"
brightCyan = "#0A6A70"
brightWhite = "#F6F8FA"
