schema-version = 1
id = "builtin.terminal.rose-pine-dawn"
name = "Rosé Pine Dawn"
kind = "terminal"
author = "Rosé Pine"
source = "https://github.com/rose-pine/rose-pine-theme"
[terminal]
background = "#FAF4ED"
foreground = "#575279"
cursorColor = "#575279"
selectionBackground = "#F0D8E8"
black = "#575279"
red = "#B4637A"
green = "#286983"
yellow = "#EA9D34"
blue = "#56949F"
purple = "#907AA9"
cyan = "#D7827E"
white = "#F2E9DE"
brightBlack = "#797593"
brightRed = "#B4637A"
brightGreen = "#286983"
brightYellow = "#EA9D34"
brightBlue = "#56949F"
brightPurple = "#907AA9"
brightCyan = "#D7827E"
brightWhite = "#FFFDFB"
